<script src="/js/pubuliu.js"></script>
<script type="text/javascript">
$(document).ready(function() {
	function resizeLoadFun(){
		
		var winWidth = $(window).width();
		var conWidth;
		if(winWidth < 496) {
			conWidth = 246;
			col = 1
		}		
		else if(winWidth < 738) {
			conWidth = 496;
			col = 2
		} else if(winWidth < 984){
			conWidth = 738;
			col = 3;
		} 
		else {
			conWidth = 984;
			col = 4;
		}
		
		if(conWidth != currentWidth) {
			currentWidth = conWidth;
			$('#container').width(conWidth);
			$('#container').BlocksIt({
				numOfCol: col,
				offsetX: 8,
				offsetY: 10
			});
		}
		
		
	}

	//blocksit define
	$(window).load( function() {
		resizeLoadFun();	
	});
	
	//window resize
	var currentWidth = 300;
	$(window).resize(function() {
		resizeLoadFun();
	});
	
	
});


</script>
<div class="row">
    <div id="container">
         <div class="grid">
             <div class="imgholder">
                 <img src="images/goods/2.jpg">
                     </div>
                     <div class="texthodler">
						<ul>
							<li class="title">
							红玫瑰代表热情真爱； 
							黄玫瑰代表珍重祝福和嫉妒失恋； 
							紫玫瑰代表浪漫真情和珍贵独特； 
							白玫瑰代表纯洁爱情； 
							黑玫瑰代表温柔真心； 
							橘红色玫瑰友情和青春美丽； 
							蓝玫瑰代表敦厚善良和独一无二
							</li>
						</ul>
					</div>
					<div class="comm_num twiiter_box">
					<a href="javascript:void(0)" class="left_f poster_likes likes ">
					<b class="likes_status">
					<i class="lm_love2">&nbsp;</i>喜欢
					</b>
					<span class="red_f">26229</span>
					</a>
					<a  href="javascript:void(0)" class="pl">销量（2002）</a>					
					</div>
         </div>
         
         <div class="grid">
             <div class="imgholder">
                 <img src="images/goods/1.jpg">
                     </div>
                     <div class="texthodler">
						<ul>
							<li class="title">
							1朵玫瑰代表——我的心中只有你 ONLY YOU！ 
							2朵玫瑰代表——这世界只有我俩！ 
							3朵玫瑰代表——我爱你 I LOVE YOU！ 
							4朵玫瑰代表——至死不渝！ 
							5朵玫瑰代表——由衷欣赏！ 
							6朵玫瑰代表——互敬 互爱 互谅！ 
							7朵玫瑰代表——我偷偷地爱著你！ 
							8朵玫瑰代表——感谢你的关怀扶持及鼓励！ 
							9朵玫瑰代表——长久 ALWAYS！ 
							 
							
							</li>
						</ul>
					</div>
					
					<div class="comm_num twiiter_box">
					<a href="javascript:void(0)" class="left_f poster_likes likes ">
					<b class="likes_status">
					<i class="lm_love2">&nbsp;</i>喜欢
					</b>
					<span class="red_f">26229</span>
					</a>
					<a  href="javascript:void(0)" class="pl">销量（2002）</a>					
					</div>
         </div><div class="grid">
             <div class="imgholder">
                 <img src="images/goods/4.jpg">
                     </div>
                     <div class="texthodler">
						<ul>
							<li class="title">
							10朵玫瑰代表——十全十美 无懈可击！ 
							11朵玫瑰代表——最爱 只在乎你一人！ 
							12朵玫瑰代表——对你的爱与日俱增！ 
							13朵玫瑰代表——友谊长存！ 
							14朵玫瑰代表——骄傲！ 
							15朵玫瑰代表——对你感到歉意I''M SORRY！ 
							16朵玫瑰代表——多变不安的爱情！ 
							17朵玫瑰代表——绝望无可挽回的爱！ 
							18朵玫瑰代表——真诚与坦白！ 
							19朵玫瑰代表——忍耐与期待！ 
							20朵玫瑰代表——我仅一颗赤诚的心！ 
							21朵玫瑰象徵——真诚的爱！
							</li>
						</ul>
					</div>
					
					<div class="comm_num twiiter_box">
					<a href="javascript:void(0)" class="left_f poster_likes likes ">
					<b class="likes_status">
					<i class="lm_love2">&nbsp;</i>喜欢
					</b>
					<span class="red_f">26229</span>
					</a>
					<a  href="javascript:void(0)" class="pl">销量（2002）</a>					
					</div>
         </div>
         
         <div class="grid">
             <div class="imgholder">
                 <img src="images/goods/3.jpg">
                     </div>
                     <div class="texthodler">
						<ul>
							<li class="title">
							22朵玫瑰象徵——祝你好运！ 
							25朵玫瑰象徵——祝你幸福！ 
							30朵玫瑰象徵——信是有缘！ 
							36朵玫瑰象徵——浪漫爱情！ 
							40朵玫瑰象徵——誓死不渝的爱情！ 
							50朵玫瑰象徵——邂逅不期而遇！ 
							99朵玫瑰象徵——天长地久 FOREVER！ 
							100朵玫瑰象徵——百分之百的爱 100% LOVE！ 
							101朵玫瑰象徵——最……最爱！ 
							108朵玫瑰象徵——求 婚！
							</li>
						</ul>
					</div>
					
					<div class="comm_num twiiter_box">
					<a href="javascript:void(0)" class="left_f poster_likes likes ">
					<b class="likes_status">
					<i class="lm_love2">&nbsp;</i>喜欢
					</b>
					<span class="red_f">26229</span>
					</a>
					<a  href="javascript:void(0)" class="pl">销量（2002）</a>					
					</div>
         </div>
         
         <div class="grid">
             <div class="imgholder">
                 <img src="images/goods/2.jpg">
                     </div>
                    <div class="texthodler">
						<ul>
							<li class="title">
							红玫瑰代表热情真爱； 
							黄玫瑰代表珍重祝福和嫉妒失恋； 
							紫玫瑰代表浪漫真情和珍贵独特； 
							白玫瑰代表纯洁爱情； 
							黑玫瑰代表温柔真心； 
							橘红色玫瑰友情和青春美丽； 
							蓝玫瑰代表敦厚善良和独一无二
							</li>
						</ul>
					</div>
					<div class="comm_num twiiter_box">
					<a href="javascript:void(0)" class="left_f poster_likes likes ">
					<b class="likes_status">
					<i class="lm_love2">&nbsp;</i>喜欢
					</b>
					<span class="red_f">26229</span>
					</a>
					<a  href="javascript:void(0)" class="pl">销量（2002）</a>					
					</div>
         </div>
         
         <div class="grid">
             <div class="imgholder">
                 <img src="images/goods/1.jpg">
                     </div>
                     <div class="texthodler">
						<ul>
							<li class="title">
							红玫瑰代表热情真爱； 
							黄玫瑰代表珍重祝福和嫉妒失恋； 
							紫玫瑰代表浪漫真情和珍贵独特； 
							白玫瑰代表纯洁爱情； 
							黑玫瑰代表温柔真心； 
							橘红色玫瑰友情和青春美丽； 
							蓝玫瑰代表敦厚善良和独一无二
							</li>
						</ul>
					</div>
					<div class="comm_num twiiter_box">
					<a href="javascript:void(0)" class="left_f poster_likes likes ">
					<b class="likes_status">
					<i class="lm_love2">&nbsp;</i>喜欢
					</b>
					<span class="red_f">26229</span>
					</a>
					<a  href="javascript:void(0)" class="pl">销量（2002）</a>					
					</div>
         </div><div class="grid">
             <div class="imgholder">
                 <img src="images/goods/4.jpg">
                     </div>
                     <div class="texthodler">
						<ul>
							<li class="title">
							红玫瑰代表热情真爱； 
							黄玫瑰代表珍重祝福和嫉妒失恋； 
							紫玫瑰代表浪漫真情和珍贵独特； 
							白玫瑰代表纯洁爱情； 
							黑玫瑰代表温柔真心； 
							橘红色玫瑰友情和青春美丽； 
							蓝玫瑰代表敦厚善良和独一无二
							</li>
						</ul>
					</div>
					<div class="comm_num twiiter_box">
					<a href="javascript:void(0)" class="left_f poster_likes likes ">
					<b class="likes_status">
					<i class="lm_love2">&nbsp;</i>喜欢
					</b>
					<span class="red_f">26229</span>
					</a>
					<a  href="javascript:void(0)" class="pl">销量（2002）</a>					
					</div>
         </div>
         
         <div class="grid">
             <div class="imgholder">
                 <img src="images/goods/3.jpg">
                     </div>
                     <div class="texthodler">
						<ul>
							<li class="title">
							红玫瑰代表热情真爱； 
							黄玫瑰代表珍重祝福和嫉妒失恋； 
							紫玫瑰代表浪漫真情和珍贵独特； 
							白玫瑰代表纯洁爱情； 
							黑玫瑰代表温柔真心； 
							橘红色玫瑰友情和青春美丽； 
							蓝玫瑰代表敦厚善良和独一无二
							</li>
						</ul>
					</div>
					<div class="comm_num twiiter_box">
					<a href="javascript:void(0)" class="left_f poster_likes likes ">
					<b class="likes_status">
					<i class="lm_love2">&nbsp;</i>喜欢
					</b>
					<span class="red_f">26229</span>
					</a>
					<a  href="javascript:void(0)" class="pl">销量（2002）</a>					
					</div>
         </div>
         
         <div class="grid">
             <div class="imgholder">
                 <img src="images/goods/2.jpg">
                     </div>
                     <div class="texthodler">
						<ul>
							<li class="title">
							红玫瑰代表热情真爱； 
							黄玫瑰代表珍重祝福和嫉妒失恋； 
							紫玫瑰代表浪漫真情和珍贵独特； 
							白玫瑰代表纯洁爱情； 
							黑玫瑰代表温柔真心； 
							橘红色玫瑰友情和青春美丽； 
							蓝玫瑰代表敦厚善良和独一无二
							</li>
						</ul>
					</div>
					<div class="comm_num twiiter_box">
					<a href="javascript:void(0)" class="left_f poster_likes likes ">
					<b class="likes_status">
					<i class="lm_love2">&nbsp;</i>喜欢
					</b>
					<span class="red_f">26229</span>
					</a>
					<a  href="javascript:void(0)" class="pl">销量（2002）</a>					
					</div>
         </div>
         
         <div class="grid">
             <div class="imgholder">
                 <img src="images/goods/1.jpg">
                     </div>
                     <div class="texthodler">
						<ul>
							<li class="title">
							红玫瑰代表热情真爱； 
							黄玫瑰代表珍重祝福和嫉妒失恋； 
							紫玫瑰代表浪漫真情和珍贵独特； 
							白玫瑰代表纯洁爱情； 
							黑玫瑰代表温柔真心； 
							橘红色玫瑰友情和青春美丽； 
							蓝玫瑰代表敦厚善良和独一无二
							</li>
						</ul>
					</div>
					<div class="comm_num twiiter_box">
					<a href="javascript:void(0)" class="left_f poster_likes likes ">
					<b class="likes_status">
					<i class="lm_love2">&nbsp;</i>喜欢
					</b>
					<span class="red_f">26229</span>
					</a>
					<a  href="javascript:void(0)" class="pl">销量（2002）</a>					
					</div>
         </div>
         <div class="grid">
             <div class="imgholder">
                 <img src="images/goods/4.jpg">
                     </div>
                    <div class="texthodler">
						<ul>
							<li class="title">
							红玫瑰代表热情真爱； 
							黄玫瑰代表珍重祝福和嫉妒失恋； 
							紫玫瑰代表浪漫真情和珍贵独特； 
							白玫瑰代表纯洁爱情； 
							黑玫瑰代表温柔真心； 
							橘红色玫瑰友情和青春美丽； 
							蓝玫瑰代表敦厚善良和独一无二
							</li>
						</ul>
					</div>
					<div class="comm_num twiiter_box">
					<a href="javascript:void(0)" class="left_f poster_likes likes ">
					<b class="likes_status">
					<i class="lm_love2">&nbsp;</i>喜欢
					</b>
					<span class="red_f">26229</span>
					</a>
					<a  href="javascript:void(0)" class="pl">销量（2002）</a>					
					</div>
         </div>
         
         <div class="grid">
             <div class="imgholder">
                 <img src="images/goods/3.jpg">
                     </div>
                     <div class="texthodler">
						<ul>
							<li class="title">
							红玫瑰代表热情真爱； 
							黄玫瑰代表珍重祝福和嫉妒失恋； 
							紫玫瑰代表浪漫真情和珍贵独特； 
							白玫瑰代表纯洁爱情； 
							黑玫瑰代表温柔真心； 
							橘红色玫瑰友情和青春美丽； 
							蓝玫瑰代表敦厚善良和独一无二
							</li>
						</ul>
					</div>
					<div class="comm_num twiiter_box">
					<a href="javascript:void(0)" class="left_f poster_likes likes ">
					<b class="likes_status">
					<i class="lm_love2">&nbsp;</i>喜欢
					</b>
					<span class="red_f">26229</span>
					</a>
					<a  href="javascript:void(0)" class="pl">销量（2002）</a>					
					</div>
         </div><div class="grid">
             <div class="imgholder">
                 <img src="images/goods/4.jpg">
                     </div>
                     <<div class="texthodler">
						<ul>
							<li class="title">
							红玫瑰代表热情真爱； 
							黄玫瑰代表珍重祝福和嫉妒失恋； 
							紫玫瑰代表浪漫真情和珍贵独特； 
							白玫瑰代表纯洁爱情； 
							黑玫瑰代表温柔真心； 
							橘红色玫瑰友情和青春美丽； 
							蓝玫瑰代表敦厚善良和独一无二
							</li>
						</ul>
					</div>
					<div class="comm_num twiiter_box">
					<a href="javascript:void(0)" class="left_f poster_likes likes ">
					<b class="likes_status">
					<i class="lm_love2">&nbsp;</i>喜欢
					</b>
					<span class="red_f">26229</span>
					</a>
					<a  href="javascript:void(0)" class="pl">销量（2002）</a>					
					</div>
         </div>
         
         <div class="grid">
             <div class="imgholder">
                 <img src="images/goods/3.jpg">
                     </div>
                     <div class="texthodler">
						<ul>
							<li class="title">
							红玫瑰代表热情真爱； 
							黄玫瑰代表珍重祝福和嫉妒失恋； 
							紫玫瑰代表浪漫真情和珍贵独特； 
							白玫瑰代表纯洁爱情； 
							黑玫瑰代表温柔真心； 
							橘红色玫瑰友情和青春美丽； 
							蓝玫瑰代表敦厚善良和独一无二
							</li>
						</ul>
					</div>
					<div class="comm_num twiiter_box">
					<a href="javascript:void(0)" class="left_f poster_likes likes ">
					<b class="likes_status">
					<i class="lm_love2">&nbsp;</i>喜欢
					</b>
					<span class="red_f">26229</span>
					</a>
					<a  href="javascript:void(0)" class="pl">销量（2002）</a>					
					</div>
         </div>
         
         <div class="grid">
             <div class="imgholder">
                 <img src="images/goods/2.jpg">
                     </div>
                    <div class="texthodler">
						<ul>
							<li class="title">
							红玫瑰代表热情真爱； 
							黄玫瑰代表珍重祝福和嫉妒失恋； 
							紫玫瑰代表浪漫真情和珍贵独特； 
							白玫瑰代表纯洁爱情； 
							黑玫瑰代表温柔真心； 
							橘红色玫瑰友情和青春美丽； 
							蓝玫瑰代表敦厚善良和独一无二
							</li>
						</ul>
					</div>
					<div class="comm_num twiiter_box">
					<a href="javascript:void(0)" class="left_f poster_likes likes ">
					<b class="likes_status">
					<i class="lm_love2">&nbsp;</i>喜欢
					</b>
					<span class="red_f">26229</span>
					</a>
					<a  href="javascript:void(0)" class="pl">销量（2002）</a>					
					</div>
         </div>
         
         <div class="grid">
             <div class="imgholder">
                 <img src="images/goods/1.jpg">
                     </div>
                     <div class="texthodler">
						<ul>
							<li class="title">
							红玫瑰代表热情真爱； 
							黄玫瑰代表珍重祝福和嫉妒失恋； 
							紫玫瑰代表浪漫真情和珍贵独特； 
							白玫瑰代表纯洁爱情； 
							黑玫瑰代表温柔真心； 
							橘红色玫瑰友情和青春美丽； 
							蓝玫瑰代表敦厚善良和独一无二
							</li>
						</ul>
					</div>
					<div class="comm_num twiiter_box">
					<a href="javascript:void(0)" class="left_f poster_likes likes ">
					<b class="likes_status">
					<i class="lm_love2">&nbsp;</i>喜欢
					</b>
					<span class="red_f">26229</span>
					</a>
					<a  href="javascript:void(0)" class="pl">销量（2002）</a>					
					</div>
         </div><div class="grid">
             <div class="imgholder">
                 <img src="images/goods/4.jpg">
                     </div>
                     <div class="texthodler">
						<ul>
							<li class="title">
							红玫瑰代表热情真爱； 
							黄玫瑰代表珍重祝福和嫉妒失恋； 
							紫玫瑰代表浪漫真情和珍贵独特； 
							白玫瑰代表纯洁爱情； 
							黑玫瑰代表温柔真心； 
							橘红色玫瑰友情和青春美丽； 
							蓝玫瑰代表敦厚善良和独一无二
							</li>
						</ul>
					</div>
					<div class="comm_num twiiter_box">
					<a href="javascript:void(0)" class="left_f poster_likes likes ">
					<b class="likes_status">
					<i class="lm_love2">&nbsp;</i>喜欢
					</b>
					<span class="red_f">26229</span>
					</a>
					<a  href="javascript:void(0)" class="pl">销量（2002）</a>					
					</div>
         </div>
         
         <div class="grid">
             <div class="imgholder">
                 <img src="images/goods/3.jpg">
                     </div>
                     <div class="texthodler">
						<ul>
							<li class="title">
							红玫瑰代表热情真爱； 
							黄玫瑰代表珍重祝福和嫉妒失恋； 
							紫玫瑰代表浪漫真情和珍贵独特； 
							白玫瑰代表纯洁爱情； 
							黑玫瑰代表温柔真心； 
							橘红色玫瑰友情和青春美丽； 
							蓝玫瑰代表敦厚善良和独一无二
							</li>
						</ul>
					</div>
					<div class="comm_num twiiter_box">
					<a href="javascript:void(0)" class="left_f poster_likes likes ">
					<b class="likes_status">
					<i class="lm_love2">&nbsp;</i>喜欢
					</b>
					<span class="red_f">26229</span>
					</a>
					<a  href="javascript:void(0)" class="pl">销量（2002）</a>					
					</div>
         </div>
         
         <div class="grid">
             <div class="imgholder">
                 <img src="images/goods/2.jpg">
                     </div>
                     <div class="texthodler">
						<ul>
							<li class="title">
							红玫瑰代表热情真爱； 
							黄玫瑰代表珍重祝福和嫉妒失恋； 
							紫玫瑰代表浪漫真情和珍贵独特； 
							白玫瑰代表纯洁爱情； 
							黑玫瑰代表温柔真心； 
							橘红色玫瑰友情和青春美丽； 
							蓝玫瑰代表敦厚善良和独一无二
							</li>
						</ul>
					</div>
					<div class="comm_num twiiter_box">
					<a href="javascript:void(0)" class="left_f poster_likes likes ">
					<b class="likes_status">
					<i class="lm_love2">&nbsp;</i>喜欢
					</b>
					<span class="red_f">26229</span>
					</a>
					<a  href="javascript:void(0)" class="pl">销量（2002）</a>					
					</div>
         </div>
         
         <div class="grid">
             <div class="imgholder">
                 <img src="images/goods/1.jpg">
                     </div>
                     <div class="texthodler">
						<ul>
							<li class="title">
							红玫瑰代表热情真爱； 
							黄玫瑰代表珍重祝福和嫉妒失恋； 
							紫玫瑰代表浪漫真情和珍贵独特； 
							白玫瑰代表纯洁爱情； 
							黑玫瑰代表温柔真心； 
							橘红色玫瑰友情和青春美丽； 
							蓝玫瑰代表敦厚善良和独一无二
							</li>
						</ul>
					</div>
					<div class="comm_num twiiter_box">
					<a href="javascript:void(0)" class="left_f poster_likes likes ">
					<b class="likes_status">
					<i class="lm_love2">&nbsp;</i>喜欢
					</b>
					<span class="red_f">26229</span>
					</a>
					<a  href="javascript:void(0)" class="pl">销量（2002）</a>					
					</div>
         </div><div class="grid">
             <div class="imgholder">
                 <img src="images/goods/4.jpg">
                     </div>
<div class="texthodler">
						<ul>
							<li class="title">
							红玫瑰代表热情真爱； 
							黄玫瑰代表珍重祝福和嫉妒失恋； 
							紫玫瑰代表浪漫真情和珍贵独特； 
							白玫瑰代表纯洁爱情； 
							黑玫瑰代表温柔真心； 
							橘红色玫瑰友情和青春美丽； 
							蓝玫瑰代表敦厚善良和独一无二
							</li>
						</ul>
					</div>
					<div class="comm_num twiiter_box">
					<a href="javascript:void(0)" class="left_f poster_likes likes ">
					<b class="likes_status">
					<i class="lm_love2">&nbsp;</i>喜欢
					</b>
					<span class="red_f">26229</span>
					</a>
					<a  href="javascript:void(0)" class="pl">销量（2002）</a>					
					</div>
         </div>
         
         <div class="grid">
             <div class="imgholder">
                 <img src="images/goods/3.jpg">
                     </div>
                     <div class="texthodler">
						<ul>
							<li class="title">
							红玫瑰代表热情真爱； 
							黄玫瑰代表珍重祝福和嫉妒失恋； 
							紫玫瑰代表浪漫真情和珍贵独特； 
							白玫瑰代表纯洁爱情； 
							黑玫瑰代表温柔真心； 
							橘红色玫瑰友情和青春美丽； 
							蓝玫瑰代表敦厚善良和独一无二
							</li>
						</ul>
					</div>
					<div class="comm_num twiiter_box">
					<a href="javascript:void(0)" class="left_f poster_likes likes ">
					<b class="likes_status">
					<i class="lm_love2">&nbsp;</i>喜欢
					</b>
					<span class="red_f">26229</span>
					</a>
					<a  href="javascript:void(0)" class="pl">销量（2002）</a>					
					</div>
         </div>
         
         <div class="grid">
             <div class="imgholder">
                 <img src="images/goods/2.jpg">
                     </div>
                     <div class="texthodler">
						<ul>
							<li class="title">
							红玫瑰代表热情真爱； 
							黄玫瑰代表珍重祝福和嫉妒失恋； 
							紫玫瑰代表浪漫真情和珍贵独特； 
							白玫瑰代表纯洁爱情； 
							黑玫瑰代表温柔真心； 
							橘红色玫瑰友情和青春美丽； 
							蓝玫瑰代表敦厚善良和独一无二
							</li>
						</ul>
					</div>
					<div class="comm_num twiiter_box">
					<a href="javascript:void(0)" class="left_f poster_likes likes ">
					<b class="likes_status">
					<i class="lm_love2">&nbsp;</i>喜欢
					</b>
					<span class="red_f">26229</span>
					</a>
					<a  href="javascript:void(0)" class="pl">销量（2002）</a>					
					</div>
         </div>
         
         <div class="grid">
             <div class="imgholder">
                 <img src="images/goods/1.jpg">
                     </div>
                     <div class="texthodler">
						<ul>
							<li class="title">
							红玫瑰代表热情真爱； 
							黄玫瑰代表珍重祝福和嫉妒失恋； 
							紫玫瑰代表浪漫真情和珍贵独特； 
							白玫瑰代表纯洁爱情； 
							黑玫瑰代表温柔真心； 
							橘红色玫瑰友情和青春美丽； 
							蓝玫瑰代表敦厚善良和独一无二
							</li>
						</ul>
					</div>
					<div class="comm_num twiiter_box">
					<a href="javascript:void(0)" class="left_f poster_likes likes ">
					<b class="likes_status">
					<i class="lm_love2">&nbsp;</i>喜欢
					</b>
					<span class="red_f">26229</span>
					</a>
					<a  href="javascript:void(0)" class="pl">销量（2002）</a>					
					</div>
         </div>
         <div class="grid">
             <div class="imgholder">
                 <img src="images/goods/4.jpg">
                     </div>
                     <div class="texthodler">
						<ul>
							<li class="title">
							红玫瑰代表热情真爱； 
							黄玫瑰代表珍重祝福和嫉妒失恋； 
							紫玫瑰代表浪漫真情和珍贵独特； 
							白玫瑰代表纯洁爱情； 
							黑玫瑰代表温柔真心； 
							橘红色玫瑰友情和青春美丽； 
							蓝玫瑰代表敦厚善良和独一无二
							</li>
						</ul>
					</div>
					<div class="comm_num twiiter_box">
					<a href="javascript:void(0)" class="left_f poster_likes likes ">
					<b class="likes_status">
					<i class="lm_love2">&nbsp;</i>喜欢
					</b>
					<span class="red_f">26229</span>
					</a>
					<a  href="javascript:void(0)" class="pl">销量（2002）</a>					
					</div>
         </div>
         
         <div class="grid">
             <div class="imgholder">
                 <img src="images/goods/3.jpg">
                     </div>
                     <div class="texthodler">
						<ul>
							<li class="title">
							红玫瑰代表热情真爱； 
							黄玫瑰代表珍重祝福和嫉妒失恋； 
							紫玫瑰代表浪漫真情和珍贵独特； 
							白玫瑰代表纯洁爱情； 
							黑玫瑰代表温柔真心； 
							橘红色玫瑰友情和青春美丽； 
							蓝玫瑰代表敦厚善良和独一无二
							</li>
						</ul>
					</div>
					<div class="comm_num twiiter_box">
					<a href="javascript:void(0)" class="left_f poster_likes likes ">
					<b class="likes_status">
					<i class="lm_love2">&nbsp;</i>喜欢
					</b>
					<span class="red_f">26229</span>
					</a>
					<a  href="javascript:void(0)" class="pl">销量（2002）</a>					
					</div>
         </div>
    </div>     
</div>